name: ci

on:
  push:
    branches:
      - "main"

jobs:
  release:
    name: release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup semantic-release
        uses: actions/setup-node@v1
        with:
          node-version: 12
        run: npm i semantic-release@v18.0.0
      - name: Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: npx semantic-release